# -*- coding: utf-8 -*-
"""pythonworkshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCLyc_t55TjB8jHXJSMy97oOasVfIl8Y

# Simple Calculator
"""

def add(x, y):
    return x + y
def subtract(x, y):
    return x - y
def multiply(x, y):
    return x * y
def divide(x, y):
    if y !=0:
        return x / y
    else:
        return "error! division by zero."
def calculator():
  print("given the number")
  print("choose operation")
  print("1. Add")
  print("2. Subtract")
  print("3. Multiply")
  print("4. Divide")
  while True:
    choice = input("Enter choice(1/2/3/4):")
    if choice in ['1','2','3','4']:
      a = float(input("Enter first number: "))
      b = float(input("Enter second number: "))

      if choice == '1':
        print(f"the result is:{add(a,b)}")
      elif choice == '2':
        print(f"the result is:{subtract(a,b)}")
      elif choice == '3':
        print(f"the result is:{multiply(a,b)}")
      elif choice == '4':
        print(f"the result is:{divide(a,b)}")
      next_calculation=input("Do you want to perfom another calculaton?(yes/No):")
      if next_calculation.lower() != 'yes':
          break
  else:
      print("Invalid Input")

calculator()

